# Generated by Django 4.0.5 on 2022-07-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_alter_rating_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
