# Generated by Django 4.0.5 on 2022-07-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0007_rename_rating_product_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='value',
        ),
    ]
